$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: secureops-deploy
endpoint_name: secureops-endpoint-v3
model: azureml:CIDDS_IDS_Model@latest
code_configuration:
  code: src
  scoring_script: score.py
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
instance_type: Standard_DS2_v2
instance_count: 1